image: quay.io/evemu/build-image:latest

build:
  stage: build
  tags:
    - ci
  script:
    - mkdir build; cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=./dist ..
    - make -j16
    - make install
    - tar -czf eve-server.tar.gz dist
  artifacts:
    paths:
    - build/eve-server.tar.gz
    