version: "2.2"
services:
  server:
    build: . #Build image from source repository
    #image: "quay.io/evemu/server:latest" #Use prebuilt image
    volumes:
      - config:/app/etc
      - server_cache:/app/server_cache
      - image_cache:/app/image_cache
    ports:
      - "26000:26000"
      - "26001:26001"
    depends_on:
      - db
  db:
    image: "quay.io/bitnami/mariadb:10.4"
    volumes:
      - db:/bitnami/mariadb
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=evemu
      - MARIADB_PASSWORD=evemu
      - MARIADB_DATABASE=evemu
volumes:
  db:
  config:
  server_cache:
  image_cache:
