DROP TABLE IF EXISTS crtClasses;

CREATE TABLE crtClasses
(
  classID INT,
  className VARCHAR(150),
  description TEXT,
  classNameID INT,
  PRIMARY KEY (classID)
);

INSERT INTO crtClasses (classID, className, description, classNameID) VALUES
(2, 'Core Fitting', 'Core Fitting', 59287),
(3, 'Core Capacitor', 'Core Capacitor', 59288),
(4, 'Core Targeting', 'Core Targeting', 59289),
(5, 'Core Navigation', 'Core Navigation', 59290),
(6, 'Core Competency', 'Core Competency', 59291),
(7, 'Core Integrity', 'Core Integrity', 59292),
(8, 'Amarr Military - Soldier', 'Amarr Military - Soldier', 59372),
(9, 'Amarr Military - Special Forces', 'Amarr Military - Special Forces', 59374),
(10, 'Amarr Industry - Engineer', 'Amarr Industry - Engineer', 59375),
(11, 'Amarr Industry - Prospector', 'Amarr Industry - Prospector', 59376),
(12, 'Amarr Business - Entrepreneur', 'Amarr Business - Entrepreneur', 59377),
(13, 'Amarr Business - Executive Commander', 'Amarr Business - Executive Commander', 59378),
(14, 'Caldari Military - Soldier', 'Caldari Military - Soldier', 59379),
(15, 'Caldari Military - Special Forces', 'Caldari Military - Special Forces', 59380),
(16, 'Caldari Industry - Engineer', 'Caldari Industry - Engineer', 59381),
(17, 'Caldari Industry - Prospector', 'Caldari Industry - Prospector', 59382),
(18, 'Caldari Business - Entrepreneur', 'Caldari Business - Entrepreneur', 59383),
(19, 'Caldari Business - Executive Commander', 'Caldari Business - Executive Commander', 59384),
(20, 'Gallente Military - Soldier', 'Gallente Military - Soldier', 59385),
(21, 'Gallente Military - Special Forces', 'Gallente Military - Special Forces', 59386),
(22, 'Gallente Industry - Engineer', 'Gallente Industry - Engineer', 59387),
(23, 'Gallente Industry - Prospector', 'Gallente Industry - Prospector', 59388),
(24, 'Gallente Business - Entrepreneur', 'Gallente Business - Entrepreneur', 59389),
(25, 'Gallente Business - Executive Commander', 'Gallente Business - Executive Commander', 59390),
(26, 'Minmatar Military - Soldier', 'Minmatar Military - Soldier', 59391),
(27, 'Minmatar Military - Special Forces', 'Minmatar Military - Special Forces', 59392),
(28, 'Minmatar Industry - Engineer', 'Minmatar Industry - Engineer', 59393),
(29, 'Minmatar Industry - Prospector', 'Minmatar Industry - Prospector', 59394),
(30, 'Minmatar Business - Entrepreneur', 'Minmatar Business - Entrepreneur', 59395),
(31, 'Minmatar Business - Executive Commander', 'Minmatar Business - Executive Commander', 59373),
(32, 'Armor Tanking', 'Armor Tanking', 59293),
(33, 'Armor Reinforcement', 'Armor Reinforcement', 59294),
(34, 'Active Shield Tanking', 'Active Shield Tanking', 59295),
(35, 'Passive Shield Tanking', 'Passive Shield Tanking', 59296),
(36, 'Shield Reinforcement', 'Shield Reinforcement', 59297),
(37, 'Hull Tanking', 'Hull Tanking', 59298),
(38, 'Logistics Chief', 'Logistics Chief', 59299),
(39, 'Turret Control', 'Turret Control', 59300),
(40, 'Frigate Energy Turrets', 'Frigate Energy Turrets', 59301),
(41, 'Frigate Advanced Pulse Turrets', 'Frigate Advanced Pulse Turrets', 59302),
(42, 'Frigate Advanced Beam Turrets', 'Frigate Advanced Beam Turrets', 59303),
(43, 'Cruiser Energy Turrets', 'Cruiser Energy Turrets', 59304),
(44, 'Cruiser Advanced Pulse Turrets', 'Cruiser Advanced Pulse Turrets', 59305),
(45, 'Cruiser Advanced Beam Turrets', 'Cruiser Advanced Beam Turrets', 59306),
(46, 'Battleship Energy Turrets', 'Battleship Energy Turrets', 59307),
(47, 'Battleship Advanced Pulse Turrets', 'Battleship Advanced Pulse Turrets', 59308),
(48, 'Battleship Advanced Beam Turrets', 'Battleship Advanced Beam Turrets', 59309),
(49, 'Frigate Hybrid Turrets', 'Frigate Hybrid Turrets', 59310),
(50, 'Frigate Advanced Blaster Turrets', 'Frigate Advanced Blaster Turrets', 59311),
(51, 'Frigate Advanced Rail Turrets', 'Frigate Advanced Rail Turrets', 59312),
(52, 'Cruiser Hybrid Turrets', 'Cruiser Hybrid Turrets', 59400),
(53, 'Cruiser Advanced Blaster Turrets', 'Cruiser Advanced Blaster Turrets', 59313),
(54, 'Cruiser Advanced Rail Turrets', 'Cruiser Advanced Rail Turrets', 59314),
(55, 'Battleship Hybrid Turrets', 'Battleship Hybrid Turrets', 59315),
(56, 'Battleship Advanced Blaster Turrets', 'Battleship Advanced Blaster Turrets', 59316),
(57, 'Battleship Advanced Rail Turrets', 'Battleship Advanced Rail Turrets', 59317),
(58, 'Frigate Projectile Turrets', 'Frigate Projectile Turrets', 59318),
(59, 'Frigate Advanced Autocannon Turrets', 'Frigate Advanced Autocannon Turrets', 59319),
(60, 'Frigate Advanced Artillery Turrets', 'Frigate Advanced Artillery Turrets', 59320),
(61, 'Cruiser Projectile Turrets', 'Cruiser Projectile Turrets', 59321),
(62, 'Cruiser Advanced Autocannon Turrets', 'Cruiser Advanced Autocannon Turrets', 59322),
(63, 'Cruiser Advanced Artillery Turrets', 'Cruiser Advanced Artillery Turrets', 59323),
(64, 'Battleship Projectile Turrets', 'Battleship Projectile Turrets', 59324),
(65, 'Battleship Advanced Autocannon Turrets', 'Battleship Advanced Autocannon Turrets', 59325),
(66, 'Battleship Advanced Artillery Turrets', 'Battleship Advanced Artillery Turrets', 59326),
(67, 'Missile Control', 'Missile Control', 59327),
(68, 'Frigate Launcher Control', 'Frigate Launcher Control', 59328),
(69, 'Frigate Advanced Standard Launchers', 'Frigate Advanced Standard Launchers', 59329),
(70, 'Frigate Advanced Rocket Launchers', 'Frigate Advanced Rocket Launchers', 59330),
(71, 'Cruiser Launcher Control', 'Cruiser Launcher Control', 59331),
(72, 'Cruiser Advanced Heavy Launchers', 'Cruiser Advanced Heavy Launchers', 59332),
(73, 'Cruiser Advanced Heavy Assault Launchers', 'Cruiser Advanced Heavy Assault Launchers', 59333),
(74, 'Battleship Launcher Control', 'Battleship Launcher Control', 59334),
(75, 'Battleship Advanced Cruise Launchers', 'Battleship Advanced Cruise Launchers', 59335),
(76, 'Battleship Advanced Siege Launchers', 'Battleship Advanced Siege Launchers', 59336),
(77, 'Drone Control', 'Drone Control', 59337),
(78, 'Combat Drone Control', 'Combat Drone Control', 59338),
(79, 'Heavy Drone Control', 'Heavy Drone Control', 59339),
(80, 'Specialist Drone Operator', 'Specialist Drone Operator', 59340),
(81, 'Elite Drone Operator', 'Elite Drone Operator', 59341),
(82, 'EWAR Operator', 'EWAR Operator', 59342),
(83, 'Cloak Operator', 'Cloak Operator', 59343),
(84, 'Target Painter Operator', 'Target Painter Operator', 59344),
(85, 'ECM Operator', 'ECM Operator', 59345),
(86, 'Sensor Dampener Operator', 'Sensor Dampener Operator', 59346),
(87, 'Tracking Disruptor Operator', 'Tracking Disruptor Operator', 59347),
(88, 'Propulsion Jammer Operator', 'Propulsion Jammer Operator', 59348),
(89, 'Interdiction Maneuvers', 'Interdiction Maneuvers', 59349),
(90, 'High-Velocity Helmsman', 'High-Velocity Helmsman', 59350),
(91, 'Cartographer', 'Cartographer', 59351),
(92, 'Wormhole Generation', 'Wormhole Generation', 59423),
(93, 'Unit Leader', 'Unit Leader', 59352),
(94, 'Tactical Commander', 'Tactical Commander', 59353),
(95, 'Battlespace Technician', 'Battlespace Technician', 59354),
(96, 'Armored Warfare Chief', 'Armored Warfare Chief', 59355),
(97, 'Information Warfare Chief', 'Information Warfare Chief', 59356),
(98, 'Siege Warfare Chief', 'Siege Warfare Chief', 59357),
(99, 'Skirmish Warfare Chief', 'Skirmish Warfare Chief', 59358),
(100, 'Fleet Co-Ordinator', 'Fleet Co-Ordinator', 59359),
(101, 'Harvesting Comptroller', 'Harvesting Comptroller', 59360),
(102, 'Resource Harvester', 'Resource Harvester', 59361),
(103, 'Mercoxit Specialist', 'Mercoxit Specialist', 59362),
(104, 'Industrial Harvesting', 'Industrial Harvesting', 59363),
(105, 'Ice Specialist', 'Ice Specialist', 59364),
(106, 'Automated Mining', 'Automated Mining', 59365),
(108, 'Refinery Foreman', 'Refinery Foreman', 59396),
(109, 'Common Ore Refiner', 'Common Ore Refiner', 59397),
(110, 'Rare Ore Refiner', 'Rare Ore Refiner', 59398),
(111, 'Production Intern', 'Production Intern', 59366),
(112, 'Production Manager', 'Production Manager', 59367),
(113, 'Research Manager', 'Research Manager', 59368),
(114, 'Field Technician', 'Field Technician', 59399),
(115, 'Business Mogul', 'Business Mogul', 59369),
(116, 'Business Tycoon', 'Business Tycoon', 59370),
(117, 'Remote Demolitions', 'Remote Demolitions', 59371),
(140, 'Colony Management', 'Colony Management', 59424),
(141, 'Planetology', 'Planetology', 59425);
