# Generated by CacheToSQL 2 on 12/12/2011 7:56:29 AM (UTC)
# Source: cacheChrDefaultOverviews
# File: 3200011.cache2

DROP TABLE IF EXISTS overviewDefaults;
DROP TABLE IF EXISTS chrDefaultOverviews;
DROP TABLE IF EXISTS blkDefaultOverviews;
CREATE TABLE blkChrDefaultOverviews (
    overviewID INT,
    overviewName TEXT,
    overviewShortName TEXT,
    overviewNameID INT,
    dataID INT,
    PRIMARY KEY (overviewID),
    INDEX overviewNameID (overviewNameID),
    INDEX dataID (dataID)
);

INSERT INTO blkChrDefaultOverviews (overviewID, overviewName, overviewShortName, overviewNameID, dataID) VALUES
(3, 'PvP', 'defaultpvp', 59570, 16533082),
(4, 'Mining', 'defaultmining', 59571, 16533083),
(5, 'WarpTo', 'defaultwarpto', 59572, 16533084),
(6, 'Loot', 'defaultloot', 59573, 16533085),
(8, 'All', 'defaultall', 59574, 16533086),
(12, 'Drones', 'defaultdrones', 59575, 16533087),
(13, 'General', 'default', 59576, 16533088);

