# Generated by CacheToSQL on 20.04.2011 17:55:38 (UTC)
# Source: charNewExtraCreationInfo.specialityskills

DROP TABLE IF EXISTS specialitySkills;
DROP TABLE IF EXISTS blkChrSpecialitySkills;
CREATE TABLE blkChrSpecialitySkills (
	specialityID INT,
	skillTypeID INT,
	levels TINYINT UNSIGNED,
	PRIMARY KEY (specialityID, skillTypeID)
);
