# Generated by CacheToSQL on 20.04.2011 18:56:28 (UTC)
# Source: config.BulkData.paperdollModifierLocations

DROP TABLE IF EXISTS paperdollModifierLocations;
CREATE TABLE paperdollModifierLocations (
    modifierLocationID INT,
    modifierKey TEXT,
    variationKey TEXT,
    PRIMARY KEY (modifierLocationID)
);

INSERT INTO paperdollModifierLocations (modifierLocationID, modifierKey, variationKey) VALUES
(2, 'topouter', 'dependants/drape'),
(3, 'makeup/implants', ''),
(4, 'accessories/earslow', ''),
(5, 'hair', ''),
(6, 'makeup/eyes', ''),
(7, 'makeup/lipstick', ''),
(8, 'makeup/blush', ''),
(9, 'makeup/eyeshadow', ''),
(10, 'outer', 'dependants/hood'),
(11, 'makeup/freckles', ''),
(12, 'accessories/nose', ''),
(13, 'accessories/nostril', ''),
(14, 'accessories/lips', ''),
(15, 'makeup/aging', ''),
(16, 'beard', ''),
(17, 'makeup/eyeliner', ''),
(18, 'makeup/eyelashes', ''),
(19, 'accessories/earshigh', ''),
(20, 'makeup/eyebrows', ''),
(21, 'accessories/glasses', ''),
(22, 'feet', ''),
(23, 'bottominner', ''),
(24, 'makeup/scarring', ''),
(25, 'bottomouter', 'dependants/boottucking'),
(26, 'topmiddle', 'dependants/drape'),
(27, 'topinner', ''),
(28, 'scars/head', ''),
(29, 'accessories/brow', ''),
(30, 'tattoo/head', ''),
(31, 'archetypes', ''),
(32, 'accessories/chin', ''),
(33, 'accessories', ''),
(34, 'accessories/piercings', '');
