#Generated By ozatomic

DROP TABLE IF EXISTS `extCrtCategories`;
CREATE TABLE IF NOT EXISTS `extCrtCategories` (
    `categoryID` tinyint(3) unsigned NOT NULL,
    `categoryNameID` int(10) unsigned DEFAULT '0',
    `dataID` int(10) unsigned DEFAULT '0',
    PRIMARY KEY (`categoryID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `extCrtCategories` VALUES
(3, 16, 22250862),
(4, 15, 16559510),
(5, 7, 34288261),
(6, 8, 16559503),
(7, 9, 16559504),
(8, 10, 16559505),
(9, 11, 16559506),
(10, 12, 16559507),
(11, 17, 22250878),
(12, 13, 16559508),
(13, 14, 16559509),
(18, 19, 16559511);
