-- phpMyAdmin SQL Dump
-- version 4.4.15.10
-- https://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 02, 2020 at 12:24 PM
-- Server version: 10.0.36-MariaDB
-- PHP Version: 5.6.36

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `evemu`
--

-- --------------------------------------------------------

--
-- Table structure for table `crpNPCWalletDivisons`
--

CREATE TABLE IF NOT EXISTS `crpNPCWalletDivisons` (
  `corporationID` int(10) unsigned NOT NULL,
  `balance1` double NOT NULL DEFAULT '0',
  `balance2` double NOT NULL DEFAULT '0',
  `balance3` double NOT NULL DEFAULT '0',
  `balance4` double NOT NULL DEFAULT '0',
  `balance5` double NOT NULL DEFAULT '0',
  `balance6` double NOT NULL DEFAULT '0',
  `balance7` double NOT NULL DEFAULT '0',
  `division1` varchar(100) DEFAULT '1st division',
  `division2` varchar(100) DEFAULT '2nd division',
  `division3` varchar(100) DEFAULT '3rd division',
  `division4` varchar(100) DEFAULT '4th division',
  `division5` varchar(100) DEFAULT '5th division',
  `division6` varchar(100) DEFAULT '6th division',
  `division7` varchar(100) DEFAULT '7th division',
  `walletDivision1` varchar(100) DEFAULT '1st wallet division',
  `walletDivision2` varchar(100) DEFAULT '2nd wallet division',
  `walletDivision3` varchar(100) DEFAULT '3rd wallet division',
  `walletDivision4` varchar(100) DEFAULT '4th wallet division',
  `walletDivision5` varchar(100) DEFAULT '5th wallet division',
  `walletDivision6` varchar(100) DEFAULT '6th wallet division',
  `walletDivision7` varchar(100) DEFAULT '7th wallet division'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='NPC Corporation Wallet Data';

--
-- Dumping data for table `crpNPCWalletDivisons`
--

INSERT INTO `crpNPCWalletDivisons` (`corporationID`, `balance1`, `balance2`, `balance3`, `balance4`, `balance5`, `balance6`, `balance7`, `division1`, `division2`, `division3`, `division4`, `division5`, `division6`, `division7`, `walletDivision1`, `walletDivision2`, `walletDivision3`, `walletDivision4`, `walletDivision5`, `walletDivision6`, `walletDivision7`) VALUES
(1000002, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Internal Security', 'Marketing', 'Legal', 'Manufacturing', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000003, 0, 0, 0, 0, 0, 0, 0, 'Public Relations', 'Distribution', 'Storage', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000004, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Marketing', 'Archives', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000005, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Distribution', 'Manufacturing', 'Astrosurvey', 'Internal Security', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000006, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Administration', 'Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000007, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Administration', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000008, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Distribution', 'Security', 'Administration', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000009, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Manufacturing', 'Personnel', 'Marketing', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000010, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Internal Security', 'Marketing', 'Manufacturing', 'R&D', 'Intelligenc', 'Public Relations', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000011, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Manufacturing', 'Marketing', 'Distribution', 'Personnel', 'Internal Security', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000012, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Storage', 'Distribution', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000013, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Storage', 'Marketing', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000014, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Storage', 'Distribution', 'Marketing', 'Administration', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000015, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Storage', 'Marketing', 'Internal Security', 'Administration', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000016, 0, 0, 0, 0, 0, 0, 0, 'Archives', 'Personnel', 'Public Relations', 'Production', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000017, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Public Relations', 'Marketing', 'Administration', 'Internal Security', 'Legal', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000018, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Marketing', 'Archives', 'Public Relations', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000019, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Personnel', 'Archives', 'Manufacturing', 'R&D', 'Internal Security', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000020, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Accounting', 'Public Relations', 'R&D', 'Production', 'Internal Security', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000021, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Archives', 'Personnel', 'Production', 'Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000022, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Marketing', 'Storage', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000023, 0, 0, 0, 0, 0, 0, 0, 'Storage', 'Distribution', 'Administration', 'Public Relations', 'Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000024, 0, 0, 0, 0, 0, 0, 0, 'Storage', 'Distribution', 'Administration', 'Public Relations', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000025, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Manufacturing', 'Internal Security', 'Intelligenc', 'Financial', 'Advisory', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000026, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Storage', 'Marketing', 'Legal', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000027, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Legal', 'Marketing', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000028, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Accounting', 'Legal', 'Advisory', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000029, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Accounting', 'Legal', 'Advisory', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000030, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Accounting', 'Legal', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000031, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Legal', 'Accounting', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000032, 0, 0, 0, 0, 0, 0, 0, 'Advisory', 'Intelligenc', 'Financial', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000033, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Legal', 'Intelligenc', 'Advisory', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000034, 0, 0, 0, 0, 0, 0, 0, 'Archives', 'Legal', 'Intelligenc', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000035, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Internal Security', 'Surveillance', 'Public Relations', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000036, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000037, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000038, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000039, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000040, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000041, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000042, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000043, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000044, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000045, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000046, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Legal', 'Intelligenc', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000047, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Surveillance', 'Intelligenc', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000048, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Financial', 'Intelligenc', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000049, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Security', 'Intelligenc', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000050, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Personnel', 'Advisory', 'Legal', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000051, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000052, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Advisory', 'Archives', 'Intelligenc', 'Legal', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000053, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Public Relations', 'Accounting', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000054, 0, 0, 0, 0, 0, 0, 0, 'Intelligenc', 'Surveillance', 'Internal Security', 'Administration', 'Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000055, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Marketing', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000056, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'R&D', 'Marketing', 'Personnel', 'Administration', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000057, 0, 0, 0, 0, 0, 0, 0, 'R&D', 'Public Relations', 'Internal Security', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000058, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Advisory', 'Distribution', 'Public Relations', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000059, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Marketing', 'Accounting', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000060, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Marketing', 'Astrosurvey', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000061, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Storage', 'Internal Security', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000062, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Archives', 'Distribution', 'Public Relations', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000063, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Marketing', 'Financial', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000064, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Public Relations', 'R&D', 'Personnel', 'Administration', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000065, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Distribution', 'Storage', 'Internal Security', 'Administration', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000066, 0, 0, 0, 0, 0, 0, 0, 'Production', 'R&D', 'Archives', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000067, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Marketing', 'Administration', 'Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000068, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Public Relations', 'Administration', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000069, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Administration', 'Security', 'Distribution', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000070, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Administration', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000071, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Marketing', 'Administration', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000072, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Storage', 'Security', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000073, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Personnel', 'Public Relations', 'Archives', 'Intelligenc', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000074, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Mining', 'Administration', 'Astrosurvey', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000075, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Distribution', 'Storage', 'Administration', 'Personnel', 'Marketing', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000076, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Distribution', 'Storage', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000077, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000078, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Accounting', 'Advisory', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000079, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Personnel', 'Archives', 'Public Relations', 'Accounting', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000080, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Advisory', 'Surveillance', 'Internal Security', 'Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000081, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Astrosurvey', 'Archives', 'Internal Security', 'Legal', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000082, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Intelligenc', 'Public Relations', 'Internal Security', 'Storage', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000083, 0, 0, 0, 0, 0, 0, 0, 'Archives', 'Accounting', 'Personnel', 'Public Relations', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000084, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000085, 0, 0, 0, 0, 0, 0, 0, 'Advisory', 'Legal', 'Personnel', 'Public Relations', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000086, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Financial', 'Legal', 'Public Relations', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000087, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Advisory', 'Public Relations', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000088, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Security', 'Public Relations', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000089, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Personnel', 'Public Relations', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000090, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Archives', 'Public Relations', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000091, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Financial', 'Public Relations', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000092, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Legal', 'Internal Security', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000093, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Intelligenc', 'Internal Security', 'Legal', 'Archives', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000094, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Storage', 'Security', 'Public Relations', 'Administration', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000095, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Storage', 'Security', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000096, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Storage', 'Security', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000097, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Security', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000098, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Security', 'Administration', 'Distribution', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000099, 0, 0, 0, 0, 0, 0, 0, 'Astrosurvey', 'Mining', 'Production', 'Storage', 'Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000100, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Public Relations', 'Intelligenc', 'Administration', 'Personnel', 'Marketing', 'Advisory', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000101, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'R&D', 'Marketing', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000102, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'R&D', 'Distribution', 'Storage', 'Marketing', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000103, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Marketing', 'Administration', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000104, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Administration', 'Public Relations', 'Distribution', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000105, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Public Relations', 'Administration', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000106, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Distribution', 'Public Relations', 'Personnel', 'Archives', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000107, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Marketing', 'Intelligenc', 'Administration', 'Archives', 'Personnel', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000108, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Marketing', 'Internal Security', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000109, 0, 0, 0, 0, 0, 0, 0, 'Production', 'R&D', 'Personnel', 'Administration', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000110, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Storage', 'Administration', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000111, 0, 0, 0, 0, 0, 0, 0, 'Distribution', 'Storage', 'Administration', 'Personnel', 'Marketing', 'Security', 'Accounting', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000112, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Accounting', 'Administration', 'Public Relations', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000113, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Advisory', 'Public Relations', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000114, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Accounting', 'Administration', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000115, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000116, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Public Relations', 'Administration', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000117, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Legal', 'Advisory', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000118, 0, 0, 0, 0, 0, 0, 0, 'Legal', 'Personnel', 'Administration', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000119, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Personnel', 'Public Relations', 'Archives', 'Advisory', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000120, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Internal Security', 'Surveillance', 'Personnel', 'Public Relations', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000121, 0, 0, 0, 0, 0, 0, 0, 'Intelligenc', 'Administration', 'Personnel', 'Surveillance', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000122, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Legal', 'Surveillance', 'Storage', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000123, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Surveillance', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000124, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Internal Security', 'Personnel', 'Surveillance', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000125, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Intelligenc', 'Public Relations', 'Archives', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000126, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Legal', 'Advisory', 'Archives', 'Intelligenc', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000127, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Personnel', 'Surveillance', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000128, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Surveillance', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000129, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Astrosurvey', 'Mining', 'Security', 'Marketing', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000130, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Personnel', 'Public Relations', 'Archives', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000131, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000132, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Accounting', 'Legal', 'Internal Security', 'Archives', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000133, 0, 0, 0, 0, 0, 0, 0, 'Storage', 'Distribution', 'Mining', 'Astrosurvey', 'Administration', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000134, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Surveillance', 'Security', 'Internal Security', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000135, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Manufacturing', 'Marketing', 'Internal Security', 'Storage', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000136, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Surveillance', 'Internal Security', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000137, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Surveillance', 'Internal Security', 'Intelligenc', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000138, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Personnel', 'Security', 'Internal Security', 'Intelligenc', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000139, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Production', 'Distribution', 'Storage', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000140, 0, 0, 0, 0, 0, 0, 0, 'Production', 'Marketing', 'Administration', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000141, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Distribution', 'Storage', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000142, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Marketing', 'Archives', 'Administration', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000143, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Advisory', 'Intelligenc', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000144, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Accounting', 'Administration', 'Archives', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000145, 0, 0, 0, 0, 0, 0, 0, 'Financial', 'Marketing', 'Manufacturing', 'Administration', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000146, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Internal Security', 'Surveillance', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000147, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Legal', 'Advisory', 'Personnel', 'Public Relations', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000148, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Distribution', 'Public Relations', 'Internal Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000149, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Surveillance', 'Internal Security', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000150, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Legal', 'Intelligenc', 'Public Relations', 'Advisory', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000151, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Archives', 'Personnel', 'R&D', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000152, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Distribution', 'Storage', 'Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000153, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Manufacturing', 'Marketing', 'Mining', 'Astrosurvey', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000154, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Mining', 'Astrosurvey', 'Security', 'R&D', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000155, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Manufacturing', 'Marketing', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000156, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Internal Security', 'Surveillance', 'Personnel', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000157, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Intelligenc', 'Production', 'Personnel', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000158, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Personnel', 'Public Relations', 'Production', 'Marketing', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000159, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Advisory', 'Storage', 'Public Relations', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000160, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'R&D', 'Personnel', 'Marketing', 'Internal Security', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000161, 0, 0, 0, 0, 0, 0, 0, 'Manufacturing', 'Marketing', 'Administration', 'Storage', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000162, 0, 0, 0, 0, 0, 0, 0, 'Command', 'Security', 'Internal Security', 'Surveillance', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000163, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Distribution', 'Storage', 'Security', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000164, 0, 0, 0, 0, 0, 0, 0, 'Administration', 'Public Relations', 'Personnel', 'Archives', 'Production', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000165, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000166, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000167, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000168, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000169, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000170, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division');
INSERT INTO `crpNPCWalletDivisons` (`corporationID`, `balance1`, `balance2`, `balance3`, `balance4`, `balance5`, `balance6`, `balance7`, `division1`, `division2`, `division3`, `division4`, `division5`, `division6`, `division7`, `walletDivision1`, `walletDivision2`, `walletDivision3`, `walletDivision4`, `walletDivision5`, `walletDivision6`, `walletDivision7`) VALUES
(1000171, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000172, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000177, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000178, 0, 0, 0, 0, 0, 0, 0, 'Advisory', '2nd division', '3ed division', '4th division', '5th division', '6th division', '7th division', 'Master Wallet', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000179, 0, 0, 0, 0, 0, 0, 0, '1st division', '2nd division', '3rd division', '4th division', '5th division', '6th division', '7th division', '1st wallet division', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000180, 0, 0, 0, 0, 0, 0, 0, '1st division', '2nd division', '3rd division', '4th division', '5th division', '6th division', '7th division', '1st wallet division', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000181, 0, 0, 0, 0, 0, 0, 0, '1st division', '2nd division', '3rd division', '4th division', '5th division', '6th division', '7th division', '1st wallet division', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division'),
(1000182, 0, 0, 0, 0, 0, 0, 0, '1st division', '2nd division', '3rd division', '4th division', '5th division', '6th division', '7th division', '1st wallet division', '2nd wallet division', '3rd wallet division', '4th wallet division', '5th wallet division', '6th wallet division', '7th wallet division');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `crpNPCWalletDivisons`
--
ALTER TABLE `crpNPCWalletDivisons`
  ADD PRIMARY KEY (`corporationID`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
